version: 2

references:
  docker-image: &docker-image
    docker:
      - image: circleci/node:10.15

  authenticate: &authenticate
    name: authenticate for npm
    command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc

  install: &install-deps
    name: install dependencies
    command: yarn

  restore-cache: &restore-cache
    keys:
    - v1-dependencies-{{ checksum "yarn.lock" }}

jobs:
  build:
    <<: *docker-image

    steps:
      - checkout
      - run: *authenticate
      - restore_cache: *restore-cache
      - run: *install-deps

      - save_cache:
          paths:
            - ./node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      - run:
          name: tests
          command: yarn ci

  publish:
    <<: *docker-image

    steps:
      - checkout
      - run: *authenticate
      - restore_cache: *restore-cache
      - run: *install-deps

      - run:
          name: build
          command: yarn build

      - run:
          name: publish
          command: npm publish --tag latest

workflows:
  version: 2
  build-and-publish:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - publish:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
